events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Tối ưu hóa hiệu năng
    sendfile        on;
    keepalive_timeout  65;
	server_tokens off;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html;
        index index.php index.html index.htm;

        location / {
            # Critical: Để WordPress có thể dùng Permalinks (link đẹp)
            try_files $uri $uri/ /index.php?$args;
        }

        # Xử lý các file PHP - Cực kỳ quan trọng
        location ~ \.php$ {
            try_files $uri =404;
            # 'wordpress' ở đây phải khớp với tên service trong docker-compose của sếp
            fastcgi_pass wordpress_app:9000; 
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Bảo mật: Không cho phép truy cập vào các file ẩn (như .htaccess)
        location ~ /\.ht {
            deny all;
        }
    }
}
